version: "3.7"

services:

  database:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      # read from .env file
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  live:
    build:
      context: ./services/recording
      dockerfile: ./Dockerfile.live
    volumes:
      - ./configs/live/config.yaml:/usr/config.yaml
    environment:
      # hard-coded since it refers to the database service above
      DB_HOST: database
      DB_PORT: 27017
      # read from .env file
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_PROVIDER_WSS_URI: ${NODE_PROVIDER_WSS_URI}
      NODE_PROVIDER_RPC_URI: ${NODE_PROVIDER_RPC_URI}
    depends_on:
      - database
