gas_pricing:
  gas_currency: "ETH"
  quote_currency: "USDT"
subscriptions:
  # USDC-WETH
  - contract_address: "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"
    event_id: "uniswap-v3-pool-swap"
  # WETH-USDT
  - contract_address: "0x11b815efB8f581194ae79006d24E0d814B7697F6"
    event_id: "uniswap-v3-pool-swap"
  # WBTC-WETH
  - contract_address: "0x4585FE77225b41b697C938B018E2Ac67Ac5a20c0"
    event_id: "uniswap-v3-pool-swap"
