name: Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      
      - name: Install dev dependencies
        run: pip install -r dev_requirements.txt
      
      # -------------------
      # Interface service
      # -------------------
      # Flake 8 Linting
      - name: Setup flake8 annotations
        uses: rbialon/flake8-annotations@v1

      - name: Linting on interface service
        working-directory: ./services/interface
        run: flake8 . --count

      # MyPy Type-Checking
      - name: Type-Checking on interface service
        working-directory: ./services/interface
        run: mypy --install-types --non-interactive .

      # PyTest Testing
      - name: Run tests on interface service
        working-directory: ./services/interface
        run: pytest .

      # --------------------
      # Recording services
      # --------------------
      # Flake 8 Linting
      - name: Linting on recording services
        working-directory: ./services/recording
        run: flake8 . --count

      # MyPy Type-Checking
      - name: Type-Checking on recording service
        working-directory: ./services/interface
        run: mypy --install-types --non-interactive .

      # PyTest Testing
      - name: Run tests on recording services
        working-directory: ./services/recording
        run: pytest .
